baseURL: http://fetzverse.com
languageCode: en-us
title: Fetzverse
theme: PaperMod
params:
   homeInfoParams:
      Title: 'ðŸ‘‹Hi'
   socialIcons:
        - name: twitter
          url: "https://twitter.com/fetzeth"
        - name: RsS
          url: "index.xml"
   ShowShareButtons: true

   ShowBreadCrumbs: true
   profileMode:
    enabled: true # needs to be explicitly set
    title: Fetzverse
    subtitle: "Where Fetzer writes about anything related to Fetzer"
    imageUrl: "avatar.gif"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      # - name: Tags
      #   url: tags
